BEGIN TRANSACTION;

INSERT INTO users (username,password_hash,role) VALUES ('user','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('admin','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_ADMIN');
INSERT INTO users (username,password_hash,role) VALUES ('landlord','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');
INSERT INTO users (username,password_hash,role) VALUES ('renter','$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC','ROLE_USER');

INSERT INTO users (username,password_hash,role) VALUES ('nickland','$2a$10$3zdeegb.fwTH4fGIDXvkPO.urWO43bseVmK8qQpDcF9te6MEaOOGa','ROLE_LANDLORD');
INSERT INTO users (username,password_hash,role) VALUES ('nickrent','$2a$10$.3Knp2eWh5t20BDXnvn.Z.hJMrIJih0U3ezrB72RPJLI0aNZjt5HO','ROLE_RENTER');

INSERT INTO users (username,password_hash,role) VALUES ('renter1','$2a$10$G6rmZAfpeJXf5vAuxQUrqu08OugaJj8uZMySHjbX6wokJ2ZUcfe0O','ROLE_RENTER');
INSERT INTO users (username,password_hash,role) VALUES ('landlord1','$2a$10$P4IPb02B6SsY74JRD.M8le30r7UDju7y2foRrbDJqTxdZlrDPLtsK','ROLE_LANDLORD');

INSERT INTO users (username,password_hash,role) VALUES ('renter2','$2a$10$k.oq4R.FAkwR8uQ4/1hAnO0W6Weh1UpW04WoZw/Yfpa9kl4Y4Bn3K','ROLE_RENTER');
INSERT INTO users (username,password_hash,role) VALUES ('renter3','$2a$10$d44g97aNBgkJQd119S8yGu17XLh6030m2Y7ZXJ9JdIatotmXjz.xC','ROLE_RENTER');
INSERT INTO users (username,password_hash,role) VALUES ('renter4','$2a$10$TVD7MhH1ubAB79z/r8e3ReojVdshTNR6O56b0x9zDg/lEOxoUMtYO','ROLE_RENTER');

INSERT INTO users (username,password_hash,role) VALUES ('landlord2','$2a$10$EB4EKs.Os3sM79.BweEbN.L7IByZN.aeNXwl369LhiQo2gR4zFsMi','ROLE_LANDLORD');
INSERT INTO users (username,password_hash,role) VALUES ('landlord3','$2a$10$Xj1PzCPO/6E8RcNe5IXkcujiGJfA1.R0nNLq5UmPXZmttUuWkBUZ.','ROLE_LANDLORD');


INSERT INTO property (landlord_user_id, renter_user_id, bedrooms, bathrooms, property_type, price, address, availability, property_desc, property_img) VALUES (5, 6, 1, 1, 'Apartment', 1000, '123 main street', true, 'A 1-bedroom, 1-bathroom apartment is a self-contained living space that features one private bedroom, a separate bathroom, and a combined living and dining area. Typically designed for individuals, couples, or small households, this apartment layout provides essential amenities while maintaining a cozy and manageable living environment. The bedroom offers privacy, while the bathroom accommodates personal hygiene needs. The living area often incorporates a kitchenette or full kitchen, as well as a space for relaxation and dining. Overall, a 1-bedroom, 1-bathroom apartment offers a comfortable and functional living arrangement within a compact footprint.', 'https://images.unsplash.com/photo-1613575831056-0acd5da8f085?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80');
INSERT INTO property (landlord_user_id, bedrooms, bathrooms, property_type, price, address, availability, property_desc, property_img) VALUES (8, 1, 1, 'Apartment', 1000, '124 main ave', true, 'A 1-bedroom, 1-bathroom apartment is a compact yet functional living space that includes one private bedroom, a single bathroom, and an integrated living and dining area. This apartment type is ideal for individuals, couples, or even small families seeking an efficient and comfortable living arrangement. The bedroom offers personal space, while the bathroom caters to essential hygiene needs. The combined living and dining area often includes a kitchenette or full kitchen, creating a central hub for relaxation, meal preparation, and socializing. In essence, a 1-bedroom, 1-bathroom apartment provides all the essentials for convenient living in a well-organized layout.', 'https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80');
INSERT INTO property (landlord_user_id, bedrooms, bathrooms, property_type, price, address, availability, property_desc, property_img) VALUES (5, 1, 2, 'Apartment', 1500, '123 second street', true, 'A 1-bedroom, 2-bathroom apartment is a thoughtfully designed living space that features one private bedroom and two separate bathrooms, along with a combined living and dining area. This apartment layout is an ideal choice for individuals, couples, or even small families seeking added convenience and functionality. The bedroom provides a personal haven, while the two bathrooms offer enhanced flexibility and ease for daily routines. The living and dining space, often incorporating a kitchenette or full kitchen, serves as a central hub for relaxation, meals, and socializing. This apartment configuration strikes a balance between practicality and comfort, providing an efficient and comfortable living arrangement.', 'https://images.unsplash.com/photo-1520699049698-acd2fccb8cc8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80');
INSERT INTO property (landlord_user_id, bedrooms, bathrooms, property_type, price, address, availability, property_desc, property_img) VALUES (5, 2, 1, 'Apartment', 2000, '183 third street', true,'A 2-bedroom, 1-bathroom apartment offers a functional and efficient living space that comprises two private bedrooms and a shared bathroom, along with a combined living and dining area. This apartment style is ideal for small families, roommates, or individuals seeking an economical yet comfortable living arrangement. Each bedroom provides a personal retreat, while the shared bathroom caters to essential needs. The living and dining area, often integrated with a kitchenette or full kitchen, serves as a central hub for relaxation, meals, and social interactions. This apartment layout strikes a balance between practicality and coziness, providing a well-organized and accommodating living environment within a compact footprint.', 'https://images.unsplash.com/photo-1605774337664-7a846e9cdf17?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1974&q=80');
INSERT INTO property (landlord_user_id, bedrooms, bathrooms, property_type, price, address, availability, property_desc, property_img) VALUES (8, 2, 2, 'Apartment', 2500, '200 long street', true, 'A 2-bedroom, 2-bathroom apartment is a spacious and versatile living unit that encompasses two private bedrooms and two separate bathrooms, alongside a combined living and dining area. This apartment style is an excellent choice for small families, roommates, or individuals seeking extra space and convenience. The two bedrooms offer individual retreats, while the two bathrooms provide added flexibility for daily routines. The living and dining area, often integrated with a well-equipped kitchen, serves as a central gathering spot for relaxation, meals, and social interactions. This apartment layout offers a harmonious blend of functionality and comfort, creating a comfortable and accommodating living environment.', 'https://images.unsplash.com/photo-1484154218962-a197022b5858?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1474&q=80');
INSERT INTO property (landlord_user_id, bedrooms, bathrooms, property_type, price, address, availability, property_desc, property_img) VALUES (5, 2, 3, 'Apartment', 3000, '457 short street',true, 'A 2-bedroom, 3-bathroom apartment is a generously proportioned and versatile living space that includes two private bedrooms and three separate bathrooms, along with a combined living and dining area. This apartment design caters to families, roommates, or those who desire extra room and convenience. Each bedroom provides a dedicated personal space, while the three bathrooms offer exceptional flexibility for daily routines. The living and dining space, often complemented by a fully-equipped kitchen, serves as a central hub for relaxation, meals, and social interactions. This apartment configuration strikes a harmonious balance between functionality and comfort, creating a spacious and accommodating living environment with ample amenities.', 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80');
INSERT INTO property (landlord_user_id, bedrooms, bathrooms, property_type, price, address, availability, property_desc, property_img) VALUES (5, 3, 3, 'Apartment', 3500, '235 orange avenue', true, 'A 3-bedroom, 3-bathroom apartment is a generously sized and versatile living arrangement that offers three private bedrooms and three separate bathrooms, complemented by a combined living and dining area. This apartment style is perfectly suited for larger families, roommates, or individuals who value spaciousness and convenience. Each bedroom provides its own personal haven, while the three bathrooms ensure convenience and flexibility for daily routines. The living and dining area, often featuring an integrated kitchen, serves as a central space for relaxation, meals, and social interactions. This apartment layout harmoniously blends practicality and comfort, creating a roomy and comfortable living environment with ample amenities to accommodate various lifestyles.', 'https://images.unsplash.com/photo-1539922631499-09155cc609a4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80');
INSERT INTO property (landlord_user_id, bedrooms, bathrooms, property_type, price, address, availability, property_desc, property_img) VALUES (5, 3, 4, 'House', 4000, '1234 Elmwood Avenue', true, 'A 3-bedroom, 4-bathroom home is a spacious and well-appointed residence featuring three private bedrooms and four separate bathrooms. This home design is ideal for larger families or those who desire ample living space and convenience. Each bedroom offers a personal retreat, while the four bathrooms ensure practicality and ease for daily routines. The home typically includes a living area, dining space, and a kitchen equipped with modern amenities. This layout allows for comfortable living, entertaining, and social interactions. With a harmonious blend of functionality and comfort, a 3-bedroom, 4-bathroom home offers a generous and welcoming living environment, suitable for various lifestyles and needs.', 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80');
INSERT INTO property (landlord_user_id, bedrooms, bathrooms, property_type, price, address, availability, property_desc, property_img) VALUES (8, 4, 4, 'House', 4500, '567 Willow Lane', true, 'A stunning 4-bedroom, 4-bathroom home overlooking the beach is a luxurious and idyllic retreat that combines spaciousness with breathtaking coastal views. This exceptional residence features four private bedrooms, each offering a personal haven, and four well-appointed bathrooms that cater to convenience and comfort. The highlight of this home is its prime location, providing panoramic vistas of the beach and ocean from various vantage points within the house.Designed to maximize the connection to nature, the living spaces are carefully arranged to capture the beauty of the sea. The open living area seamlessly integrates with the dining and kitchen spaces, creating an inviting environment for relaxation and entertaining. Floor-to-ceiling windows or expansive balconies offer uninterrupted views of the sparkling water, creating a sense of serenity and tranquility.With its elegant design and coastal charm, this home presents a harmonious blend of luxury and nature. It''s an ideal haven for those who seek a serene and lavish living experience with the captivating allure of the beach just beyond their doorstep.', 'https://images.unsplash.com/photo-1613545325278-f24b0cae1224?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80');
INSERT INTO property (landlord_user_id, bedrooms, bathrooms, property_type, price, address, availability, property_desc, property_img) VALUES (5, 4, 5, 'House', 5000, '890 Pinehurst Street', true, 'A splendid 4-bedroom, 5-bathroom home nestled in a charming and desirable neighborhood offers an inviting and spacious living environment. With four private bedrooms providing ample personal space, and five well-appointed bathrooms ensuring convenience, this home is tailored for comfort and practicality.Situated in a lovely neighborhood known for its beauty and tranquility, this residence is surrounded by lush greenery and manicured landscapes. The home''s design seamlessly blends modern elegance with a warm, welcoming atmosphere. The living spaces are thoughtfully arranged, featuring a cozy living area, a dining space perfect for gatherings, and a fully equipped kitchen that caters to culinary enthusiasts.The five bathrooms offer extra convenience, ensuring that there''s never a shortage of facilities during busy mornings or when hosting guests. The extra bathroom is a luxury that enhances the overall functionality of the home.This home serves as a serene retreat while still being in close proximity to local amenities and attractions. With its combination of comfort, practicality, and the allure of a wonderful neighborhood, this 4-bedroom, 5-bathroom residence embodies the ideal blend of modern living and community charm', 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80');
INSERT INTO property (landlord_user_id, bedrooms, bathrooms, property_type, price, address, availability, property_desc, property_img) VALUES (5, 5, 5, 'House', 5500, '2468 Maple Court', true, 'A grand 5-bedroom, 5-bathroom home offers an expansive and luxurious living experience. With five private bedrooms and five well-appointed bathrooms, this home is designed for those who value space, comfort, and versatility. Elegance abounds in every corner of this residence, which boasts a sophisticated design that seamlessly combines classic aesthetics with modern amenities. Each bedroom offers a personal haven, allowing for privacy and relaxation. The five bathrooms are meticulously designed, catering to convenience and ensuring there''s never a shortage of facilities.The living spaces are generously proportioned, creating an inviting atmosphere for both everyday living and entertaining. A spacious living area, a formal dining space, and a gourmet kitchen equipped with top-of-the-line appliances provide the perfect setting for hosting gatherings or simply enjoying quality time with loved ones.The exterior of the home is equally impressive, often featuring lush landscaping, outdoor entertaining areas, and possibly a pool or garden. Whether located in a serene suburb or a prestigious urban enclave, this home is a statement of luxury and refinement, offering ample space for various lifestyle needs and creating a true haven of opulence.', 'https://images.unsplash.com/photo-1596204976717-1a9ff47f74ef?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80');
INSERT INTO property (landlord_user_id, bedrooms, bathrooms, property_type, price, address, availability, property_desc, property_img) VALUES (5, 5, 6, 'House', 6000, '101 Sunflower Drive', true, 'A prestigious 5-bedroom, 6-bathroom home epitomizes grandeur and luxury. This exceptional residence boasts five private bedrooms and six meticulously designed bathrooms, creating a haven of opulence and comfort.Set within an upscale neighborhood, this home stands as a symbol of sophistication and elegance. Each bedroom is a sanctuary of its own, offering space and tranquility. The six bathrooms are tastefully appointed, ensuring convenience and indulgence at every turn. The living spaces exude refinement, with spacious rooms that seamlessly blend style and functionality. A lavish living area, a formal dining space, and a state-of-the-art kitchen create the perfect ambiance for entertaining guests and spending quality time with family.Beyond its interiors, the home''s exterior is equally impressive. Landscaped gardens, outdoor lounging areas, and perhaps a pool or spa provide a retreat-like atmosphere that extends the luxury of the indoors to the outdoors. From its architectural design to its high-end finishes, this home showcases the pinnacle of modern living. Whether located in an exclusive gated community or a prestigious urban locale, this 5-bedroom, 6-bathroom residence offers an unparalleled living experience, embodying sophistication, comfort, and a truly lavish lifestyle.', 'https://images.unsplash.com/photo-1585412727339-54e4bae3bbf9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80');



COMMIT TRANSACTION;
